import type { Metadata } from 'next';
import { ThemeProvider } from '@/providers/ThemeProvider';
import './globals.css';
import LazyMotionProvider from '@/providers/LazyMotionProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <LazyMotionProvider>
          <ThemeProvider> {children}</ThemeProvider>
        </LazyMotionProvider>
      </body>
    </html>
  );
}
